FROM python:3.8-alpine3.16

WORKDIR /home/installation

COPY requirements requirements

RUN python -m venv venv \
    && venv/bin/pip3 install -r requirements.txt \
    && chown -R microblog:microblog ./



WORKDIR /home/microblog
