FROM python:3.8-alpine3.16
RUN adduser -D microblog

WORKDIR /home/microblog

COPY requirements.txt microblog.py boot.sh ./
COPY requirements requirements

RUN python -m venv venv \
&& venv/bin/pip3 install -r requirements.txt \
&& chown -R microblog:microblog ./


COPY migrations migrations
COPY app app


ENV FLASK_APP microblog.py

RUN chown -R microblog:microblog app migrations \
&& chmod +x boot.sh

USER microblog

EXPOSE 5000

ENTRYPOINT [ "./boot.sh" ]
