ansible_python_interpreter: /usr/bin/python3
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - python3-pip
  - virtualenv
  - python3-setuptools

docker_install:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-compose-plugin

docker_pip:
  - docker
