---
- name: update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: yes

- name: install packages
  apt:
    name: "{{ packages }}"
    state: present

- name: add GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: add docker repository to apt
  apt_repository:
    repo: deb https://download.docker.com/linux/debian buster stable
    state: present

- name: install docker python modules
  pip:
    name: "{{ docker_pip }}"
    state: present
    executable: pip3

- name: install docker
  apt:
    name: "{{ docker_install }}"
    state: present

- name: start and enable docker
  service:
    name: docker
    state: started
    enabled: yes

- name: docker login
  docker_login:
    username: "{{ docker_username }}"
    password: "{{ docker_password }}"

- name: start docker container for microblog
  docker_container:
    name: microblog
    image: eddie66/microblog:flask-exporter
    ports:
      - "8000:5000"
    env:
      DATABASE_URL: "mysql+pymysql://microblog:{{ database_password }}@{{ groups['database'][0] }}:3306/microblog"
    restart_policy: always