---
# -   name: Set root password
#     user:
#         name: root
#         password: "{{ root_password }}"

# -   name: Remove apt lock file
#     file:
#         state: absent
#         path: "/var/lib/dpkg/lock-frontend"
#     become: true
#     tags: apt

# -   name: Update apt-cache and upgrade
#     apt:
#         force_apt_get: yes
#         update_cache: True
#         cache_valid_time: 3600
#         upgrade: yes

# -   name: Install packages
#     apt:
#         force_apt_get: yes
#         name: "{{ packages }}"

# -   name: copy unattended upgrades 10 settings
#     copy:
#         src: files/apt_periodic
#         dest: /etc/apt/apt.conf.d/10periodic

# -   name: copy unattended upgrades 50 settings
#     copy:
#         src: files/apt_periodic_50
#         dest: /etc/apt/apt.conf.d/50unattended-upgrades

# -   name: create user
#     user:
#         name: "{{ server_user }}"
#         password: "{{ server_user_pass }}"
#         state: present
#         shell: /bin/bash
#         groups: "{{ server_user_groups }}"

# -   name: add ssh-key for user
#     authorized_key:
#         user: "{{ server_user }}"
#         state: present
#         key: "{{ lookup('file', item) }}"
#     with_items: "{{ pub_ssh_key_location }}"

# -   name: Disallow root ssh access
#     lineinfile:
#         path: /etc/ssh/sshd_config
#         regexp: "^PermitRootLogin"
#         line: "PermitRootLogin no"
#         state: present
#     notify:
#         - restart ssh

# -   name: Disallow root ssh access
#     lineinfile:
#         path: /etc/ssh/sshd_config
#         regexp: "^PasswordAuthentication"
#         line: "PasswordAuthentication no"
#         state: present
#     notify:
#         - restart ssh

# -   meta: flush_handlers

# -   name: Add user to sudoers
#     lineinfile:
#         dest: /etc/sudoers
#         regexp: "{{ server_user }} ALL"
#         line: "{{ server_user }} ALL=(ALL) NOPASSWD:ALL"
#         state: present

# -   name: only allow user to ssh
#     lineinfile:
#         path: /etc/ssh/sshd_config
#         regexp: "^AlllowUsers"
#         line: "AlllowUsers {{ server_user }}"
#         state: present
#     ignore_errors: yes

-   name: remove default user
    remote_user: "{{ server_user }}"
    user:
        name: admin
        state: absent
        force: yes
        remove: yes